# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-03 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emoticon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=40, null=True)),
                ('emotion', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
