# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-03 01:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0002_emoticon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emoticon',
            old_name='color',
            new_name='mcolor',
        ),
        migrations.RenameField(
            model_name='emoticon',
            old_name='emotion',
            new_name='memotion',
        ),
    ]
