# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-03 02:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0003_auto_20161003_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_Verb', models.CharField(blank=True, max_length=100, null=True)),
                ('mood_Amount', models.FloatField(default=0, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mood.Emoticon')),
            ],
        ),
    ]
