# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-17 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0004_emotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerbList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verblist', models.TextField(max_length=1000, unique=True)),
            ],
        ),
    ]
