# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-27 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0006_moodcalendar'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=2000)),
            ],
        ),
        migrations.RenameField(
            model_name='moodcalendar',
            old_name='verblist',
            new_name='moodid',
        ),
    ]
