# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-29 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0009_resulttext_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2000)),
                ('category', models.CharField(choices=[('angry', '화남'), ('boring', '지루함'), ('disgust', '혐오스러움'), ('fear', '무서움'), ('happy', '행복함'), ('interesting', '재미있어요'), ('sadness', '슬퍼요'), ('surprise', '놀라워요')], default='', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='resultText',
        ),
    ]
