# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-29 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0010_auto_20161029_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotiontext',
            name='category',
            field=models.CharField(choices=[('angry', '화남'), ('boring', '지루함'), ('disgust', '혐오스러움'), ('fear', '무서움'), ('happy', '행복함'), ('interesting', '재미있어요'), ('sadness', '슬퍼요'), ('surprise', '놀라워요')], default='', max_length=20),
        ),
    ]
