# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-29 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0011_auto_20161029_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downtext',
            name='category',
            field=models.CharField(choices=[('red', '화남'), ('purple', '지루함'), ('magenta', '혐오스러움'), ('green', '무서움'), ('yellow', '행복함'), ('orange', '흥미'), ('blue', '슬퍼요'), ('skyblue', '놀라워요')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='emotiontext',
            name='category',
            field=models.CharField(choices=[('red', '화남'), ('purple', '지루함'), ('magenta', '혐오스러움'), ('green', '무서움'), ('yellow', '행복함'), ('orange', '흥미'), ('blue', '슬퍼요'), ('skyblue', '놀라워요')], default='', max_length=20),
        ),
    ]
