# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-12 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0012_auto_20161029_1609'),
    ]

    operations = [
        migrations.DeleteModel(
            name='moodCalendar',
        ),
    ]
