# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-11 11:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCalendar',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('moodDate', models.DateTimeField(auto_now_add=True)),
                ('moodid', models.CharField(max_length=1000)),
                ('color', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('maxNum', models.FloatField(default=0, null=True)),
                ('minNum', models.FloatField(default=0, null=True)),
            ],
        ),
    ]
