# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-12 20:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moodcalendar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycalendar',
            name='user',
        ),
        migrations.DeleteModel(
            name='MyCalendar',
        ),
    ]
