# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-12 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moodcalendar', '0002_auto_20161112_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=40)),
                ('moodDate', models.DateTimeField(auto_now_add=True)),
                ('moodid', models.CharField(max_length=1000)),
                ('color', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('maxNum', models.FloatField(default=0, null=True)),
                ('minNum', models.FloatField(default=0, null=True)),
            ],
        ),
    ]
