# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-14 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodcalendar', '0004_auto_20161113_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycalendar',
            name='mydiary',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='mycalendar',
            name='moodDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
