# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-19 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodcalendar', '0005_auto_20161114_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=40)),
                ('moodDate', models.DateTimeField(unique=True)),
                ('memo', models.TextField(default=0, null=True)),
            ],
        ),
    ]
