# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-19 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodcalendar', '0006_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='moodDate',
            field=models.DateTimeField(),
        ),
    ]
