# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-19 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodcalendar', '0008_auto_20161119_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='moodDate',
            field=models.CharField(max_length=20),
        ),
    ]
