# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-20 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodcalendar', '0009_auto_20161119_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='memo',
            field=models.TextField(default=''),
        ),
    ]
