# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-20 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodcalendar', '0010_auto_20161120_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycalendar',
            name='moodDate',
            field=models.DateTimeField(),
        ),
    ]
