# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-20 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodcalendar', '0011_auto_20161120_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycalendar',
            name='moodDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
