# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-07 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='KaKAoMood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=10)),
            ],
        ),
    ]
